# Generated by Django 5.0.2 on 2024-03-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0002_alunos_professor_salas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('professores', models.ManyToManyField(related_name='alunos', to='polly.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('professor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala', to='polly.professor')),
            ],
        ),
        migrations.DeleteModel(
            name='Alunos',
        ),
        migrations.DeleteModel(
            name='Salas',
        ),
    ]
