# Generated by Django 5.0.2 on 2024-03-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0003_aluno_sala_delete_alunos_delete_salas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='professores',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='professor',
        ),
        migrations.CreateModel(
            name='Manejamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno', models.ManyToManyField(related_name='professor', to='polly.aluno')),
                ('professor', models.ManyToManyField(related_name='aluno', to='polly.professor')),
                ('sala', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor', to='polly.sala')),
            ],
        ),
    ]
