# Generated by Django 5.0.2 on 2024-03-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0004_remove_aluno_professores_remove_sala_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunos', models.ManyToManyField(related_name='alunos', to='polly.professor')),
                ('sala', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala', to='polly.professor')),
            ],
        ),
        migrations.DeleteModel(
            name='Manejamento',
        ),
    ]
