# Generated by Django 5.0.2 on 2024-03-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0006_aluno_professores_sala_professor_delete_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
