# Generated by Django 5.0.2 on 2024-03-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0007_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
