# Generated by Django 5.0.2 on 2024-03-21 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0009_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='professores',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='professor',
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polly.aluno'),
        ),
        migrations.AlterField(
            model_name='show',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polly.professor'),
        ),
        migrations.AlterField(
            model_name='show',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polly.sala'),
        ),
    ]
